name: Prueba pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  saludo1:
    name: Job de saludo 1
    runs-on: ubuntu-latest
    steps:
      - name: primer saludo
        run: echo "Hola mundo 1"
      - name: segundo saludo
        run: echo "Hola mundo 2"
      - name: tercer saludo
        run: echo "Hola mundo 3"
  
  saludo2:
    name: Job de saludo 2
    runs-on: ubuntu-latest
    needs: ["saludo1"]
    steps:
      - name: primer saludo
        run: echo "Hola mundo 1"
      - name: segundo saludo
        run: echo "Hola mundo 2"
      - name: tercer saludo
        run: echo "Hola mundo 3"
