name: Prueba pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  saludo:
    name: Job de saludo
    runs-on: ubuntu-latest
    steps:
      - name: primer saludo
        run: echo "Hola mundo 1"
      - name: segundo saludo
        run: echo "Hola mundo 2"
      - name: tercer saludo
        run: echo "Hola mundo 3"
